name: blptl
channels:
  - conda-forge
  - pytorch
  - defaults
  - numerics88
dependencies:
  - python=3.7
  - nomkl
  - numpy
  - scipy
  - pandas
  - vtk
  - n88tools
  - matplotlib
  - pytorch
  - torchvision
  - pytorch-lightning
  - torchmetrics